"""Deterministic Phase 3/3.5 golden-case fixture generator.

Writes tests/fixtures/post_publication_pipeline/:
  - README.md
  - case_catalog.json            (end-to-end Cases A-L)
  - golden_coverage_cases.json   (20 cases, Phase 3.5 authoritative semantics)
  - golden_snapshot_cases.json   (20 cases)
  - golden_trigger_cases.json    (15 cases)

And tests/fixtures/election_candidates/coverage_semantic_golden_v1.json
(30 coverage semantic cases: 20 calibration + 10 holdout).

No real production event IDs and no dependency on wall-clock time are used.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / "fixtures" / "post_publication_pipeline"
SEMANTIC_OUT = ROOT / "tests" / "fixtures" / "election_candidates"


def _evt(eid, occurred_at, event_type="campaign_event"):
    return {"event_id": eid, "occurred_at": occurred_at, "event_type": event_type}


def _poll(pid, field_end):
    return {
        "poll_id": pid,
        "fieldwork_json": json.dumps({"field_end": field_end}, ensure_ascii=False),
        "publication_json": "{}",
    }


def build_coverage_cases() -> list[dict]:
    """20 Phase 3.5 coverage golden cases.

    Authoritative semantics: facts_cutoff is supplied research state; latest_event_date
    is MAX(event date); no-event days and missing polls never create coverage gaps;
    status full requires cutoff>=period_end and no blocking gaps.
    """
    return [
        {"case_id": "cov_01_complete_date", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g1", "2026-07-10T00:00:00+08:00", "campaign_event")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-10",
         "expected_event_count": 1, "expected_uncovered_count": 0, "expected_status": "full"},
        {"case_id": "cov_02_imprecise_date", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g2", "2026-07-20T00:00:00+08:00", "party_nomination")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-20",
         "expected_event_count": 1, "expected_uncovered_count": 0, "expected_status": "full"},
        {"case_id": "cov_03_multi_source", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g3", "2026-07-15T00:00:00+08:00", "campaign_event")],
         "polls": [], "event_source_ids": [
             {"event_id": "evt_g3", "source_id": "src_a"},
             {"event_id": "evt_g3", "source_id": "src_b"}],
         "source_count": 3, "facts_cutoff": "2026-07-31",
         "expected_covered_sources": ["src_a", "src_b"], "expected_source_count": 3,
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-15",
         "expected_event_count": 1, "expected_uncovered_count": 0, "expected_status": "full"},
        {"case_id": "cov_04_multi_event_same_day", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g4a", "2026-07-18T09:00:00+08:00", "poll_release"),
                    _evt("evt_g4b", "2026-07-18T18:00:00+08:00", "campaign_event")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-18",
         "expected_event_count": 2, "expected_uncovered_count": 0, "expected_status": "full",
         "expected_covered_dates": ["2026-07-18"]},
        {"case_id": "cov_05_reviewed_no_material_event", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g5", None)], "polls": [], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": None,
         "expected_event_count": 0, "expected_uncovered_count": 0, "expected_status": "full"},
        {"case_id": "cov_06_poll_release_vs_fieldwork", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [], "polls": [_poll("poll_g6", "2026-07-05")], "facts_cutoff": "2026-07-31",
         "expected_poll_cutoff": "2026-07-05", "expected_status": "full",
         "expected_uncovered_count": 0, "expected_blocking_count": 0},
        {"case_id": "cov_07_poll_outside_period", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [], "polls": [_poll("poll_g7", "2026-06-30")], "facts_cutoff": "2026-07-31",
         "expected_poll_cutoff": None, "expected_status": "full", "expected_uncovered_count": 0},
        {"case_id": "cov_08_period_boundary", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g8a", "2026-07-01T00:00:00+08:00"),
                    _evt("evt_g8b", "2026-07-31T23:59:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_event_count": 2, "expected_facts_cutoff": "2026-07-31",
         "expected_latest_event_date": "2026-07-31", "expected_uncovered_count": 0,
         "expected_status": "full"},
        {"case_id": "cov_09_month_end_full", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g9", "2026-07-31T00:00:00+08:00", "governance_event")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-31",
         "expected_uncovered_count": 0, "expected_status": "full"},
        {"case_id": "cov_10_cross_month", "period_start": "2026-06-16", "period_end": "2026-07-15",
         "events": [_evt("evt_g10a", "2026-06-30T00:00:00+08:00"),
                    _evt("evt_g10b", "2026-07-15T00:00:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-15",
         "expected_event_count": 2, "expected_facts_cutoff": "2026-07-15",
         "expected_latest_event_date": "2026-07-15", "expected_uncovered_count": 0,
         "expected_status": "full"},
        {"case_id": "cov_11_facts_cutoff_period_end", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g11", "2026-07-31T00:00:00+08:00", "disaster_response")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_uncovered_count": 0},
        {"case_id": "cov_12_poll_cutoff_early", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g12", "2026-07-30T00:00:00+08:00", "poll_release")],
         "polls": [_poll("poll_g12", "2026-07-12")], "facts_cutoff": "2026-07-31",
         "expected_facts_cutoff": "2026-07-31", "expected_poll_cutoff": "2026-07-12",
         "expected_status": "full", "expected_uncovered_count": 0, "expected_poll_count": 1},
        {"case_id": "cov_13_blocking_gap", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g13a", "2026-07-05T00:00:00+08:00"),
                    _evt("evt_g13b", "2026-07-10T00:00:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "blocking_gaps": [{"kind": "missing_required_dimension", "reason": "theme gap"}],
         "expected_status": "partial", "expected_blocking_count": 1},
        {"case_id": "cov_14_no_event_day_non_blocking", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g14a", "2026-07-05T00:00:00+08:00"),
                    _evt("evt_g14b", "2026-07-07T00:00:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "known_gaps": ["2026-07-06 reviewed_no_material_event"],
         "expected_status": "full", "expected_uncovered_count": 0,
         "expected_known_gaps": ["2026-07-06 reviewed_no_material_event"]},
        {"case_id": "cov_15_required_dimension_gap", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g15", "2026-07-20T00:00:00+08:00", "campaign_event")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "dimensions": ["campaign_event", "poll_release"],
         "expected_dimension_gaps": ["poll_release"], "expected_status": "partial",
         "expected_blocking_count": 1},
        {"case_id": "cov_16_known_gaps_preserved", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g16", "2026-07-20T00:00:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "known_gaps": ["manual research gap"],
         "expected_known_gaps": ["manual research gap"], "expected_status": "full"},
        {"case_id": "cov_17_events_outside_period", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g17a", "2026-06-30T00:00:00+08:00"),
                    _evt("evt_g17b", "2026-08-01T00:00:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_event_count": 0, "expected_latest_event_date": None,
         "expected_status": "full", "expected_uncovered_count": 0},
        {"case_id": "cov_18_source_count", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g18", "2026-07-20T00:00:00+08:00")],
         "polls": [], "source_count": 7, "facts_cutoff": "2026-07-31",
         "expected_source_count": 7, "expected_status": "full"},
        {"case_id": "cov_19_unreviewed_period", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g19", "2026-07-27T00:00:00+08:00")],
         "polls": [], "facts_cutoff": "2026-07-27",
         "expected_facts_cutoff": "2026-07-27", "expected_latest_event_date": "2026-07-27",
         "expected_status": "partial", "expected_uncovered_count": 1,
         "expected_blocking_count": 1,
         "expected_uncovered_contains": "2026-07-28"},
        {"case_id": "cov_20_idempotent", "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("evt_g20", "2026-07-20T00:00:00+08:00", "campaign_event")],
         "polls": [], "facts_cutoff": "2026-07-31",
         "expected_status": "full", "expected_idempotent": True},
    ]


def build_snapshot_cases() -> list[dict]:
    base_state = {
        "milestone_events": [],
        "candidate_status": "unknown",
        "structural_lean": "unknown",
        "competitiveness": "unknown",
    }
    return [
        {"case_id": "snap_01_no_new_events", "previous_state": base_state,
         "previous_supporting": ["evt_fix_nom"], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": [], "events_by_id": {}, "coverage": {"coverage_version": "fact_coverage_20260727_v001",
         "built_from_formal_state_hash": "h1"}, "as_of": "2026-08-01", "refresh_batch_id": "dr_a",
         "expected_change_required": False, "expected_review": False},
        {"case_id": "snap_02_deterministic_milestone", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g2"], "events_by_id": {"evt_g2": _evt("evt_g2", "2026-08-02", "primary_result")},
         "coverage": {"coverage_version": "fact_coverage_20260802_v001", "built_from_formal_state_hash": "h2"},
         "as_of": "2026-08-02", "refresh_batch_id": "dr_b",
         "expected_change_required": True, "expected_auto": True, "expected_review": False,
         "expected_change_type": "deterministic_append"},
        {"case_id": "snap_03_analytical_review", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g3"], "events_by_id": {"evt_g3": _evt("evt_g3", "2026-08-03", "campaign_event")},
         "coverage": {"coverage_version": "fact_coverage_20260803_v001", "built_from_formal_state_hash": "h3"},
         "as_of": "2026-08-03", "refresh_batch_id": "dr_c",
         "expected_change_required": True, "expected_auto": False, "expected_review": True},
        {"case_id": "snap_04_milestone_plus_analytical", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g4a", "evt_g4b"],
         "events_by_id": {"evt_g4a": _evt("evt_g4a", "2026-08-04", "primary_result"),
                          "evt_g4b": _evt("evt_g4b", "2026-08-04", "poll_release")},
         "coverage": {"coverage_version": "fact_coverage_20260804_v001", "built_from_formal_state_hash": "h4"},
         "as_of": "2026-08-04", "refresh_batch_id": "dr_d",
         "expected_change_required": True, "expected_auto": False, "expected_review": True},
        {"case_id": "snap_05_no_dimension_impact", "previous_state": base_state,
         "previous_supporting": ["old"], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g5"], "events_by_id": {"evt_g5": _evt("evt_g5", "2026-08-05", "primary_registration")},
         "coverage": {"coverage_version": "fact_coverage_20260805_v001", "built_from_formal_state_hash": "h5"},
         "as_of": "2026-08-05", "refresh_batch_id": "dr_e",
         "expected_change_required": False, "expected_review": False},
        {"case_id": "snap_06_unknown_type", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g6"], "events_by_id": {"evt_g6": _evt("evt_g6", "2026-08-06", "unknown")},
         "coverage": {"coverage_version": "fact_coverage_20260806_v001", "built_from_formal_state_hash": "h6"},
         "as_of": "2026-08-06", "refresh_batch_id": "dr_f",
         "expected_change_required": False, "expected_review": False},
        {"case_id": "snap_07_merge_milestones", "previous_state": {**base_state, "milestone_events": ["old_m"]},
         "previous_supporting": ["old_m"], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g7"], "events_by_id": {"evt_g7": _evt("evt_g7", "2026-08-07", "primary_result")},
         "coverage": {"coverage_version": "fact_coverage_20260807_v001", "built_from_formal_state_hash": "h7"},
         "as_of": "2026-08-07", "refresh_batch_id": "dr_g",
         "expected_change_required": True, "expected_auto": True,
         "expected_milestones": ["evt_g7", "old_m"]},
        {"case_id": "snap_08_missing_event", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_missing"], "events_by_id": {},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-08", "refresh_batch_id": "dr_h", "expected_error": "not found"},
        {"case_id": "snap_09_id_increment", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v3",
         "new_event_ids": ["evt_g9"], "events_by_id": {"evt_g9": _evt("evt_g9", "2026-08-09", "primary_result")},
         "coverage": {"coverage_version": "fact_coverage_20260809_v001", "built_from_formal_state_hash": "h9"},
         "as_of": "2026-08-09", "refresh_batch_id": "dr_i",
         "expected_change_required": True, "expected_candidate_id": "tn_state_20260809_v4"},
        {"case_id": "snap_10_id_stable", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g10"], "events_by_id": {"evt_g10": _evt("evt_g10", "2026-08-10", "primary_result")},
         "coverage": {"coverage_version": "fact_coverage_20260810_v001", "built_from_formal_state_hash": "h10"},
         "as_of": "2026-08-10", "refresh_batch_id": "dr_j",
         "expected_change_required": True, "expected_candidate_id": "tn_state_20260810_v2"},
        {"case_id": "snap_11_supporting_accumulate", "previous_state": base_state,
         "previous_supporting": ["a", "b"], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g11"], "events_by_id": {"evt_g11": _evt("evt_g11", "2026-08-11", "primary_result")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-11", "refresh_batch_id": "dr_k",
         "expected_change_required": True, "expected_supporting": ["a", "b", "evt_g11"]},
        {"case_id": "snap_12_analytical_unchanged", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g12"], "events_by_id": {"evt_g12": _evt("evt_g12", "2026-08-12", "campaign_event")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-12", "refresh_batch_id": "dr_l",
         "expected_change_required": True, "expected_review": True,
         "expected_new_value": "unchanged_pending_review"},
        {"case_id": "snap_13_no_previous_id", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "",
         "new_event_ids": ["evt_g13"], "events_by_id": {"evt_g13": _evt("evt_g13", "2026-08-13", "primary_result")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-13", "refresh_batch_id": "dr_m",
         "expected_change_required": True, "expected_candidate_id": "tn_state_20260813_v1"},
        {"case_id": "snap_14_nomination_review", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g14"], "events_by_id": {"evt_g14": _evt("evt_g14", "2026-08-14", "party_nomination")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-14", "refresh_batch_id": "dr_n",
         "expected_change_required": True, "expected_review": True, "expected_auto": False},
        {"case_id": "snap_15_launch_review", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g15"], "events_by_id": {"evt_g15": _evt("evt_g15", "2026-08-15", "campaign_launch")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-15", "refresh_batch_id": "dr_o",
         "expected_change_required": True, "expected_review": True},
        {"case_id": "snap_16_alliance_agreement", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g16"], "events_by_id": {"evt_g16": _evt("evt_g16", "2026-08-16", "alliance_agreement")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-16", "refresh_batch_id": "dr_p",
         "expected_change_required": True, "expected_auto": True, "expected_review": False},
        {"case_id": "snap_17_announcement", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g17"], "events_by_id": {"evt_g17": _evt("evt_g17", "2026-08-17", "candidate_announcement")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-17", "refresh_batch_id": "dr_q",
         "expected_change_required": True, "expected_auto": True},
        {"case_id": "snap_18_governance_review", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g18"], "events_by_id": {"evt_g18": _evt("evt_g18", "2026-08-18", "governance_event")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-18", "refresh_batch_id": "dr_r",
         "expected_change_required": True, "expected_review": True},
        {"case_id": "snap_19_disaster_review", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g19"], "events_by_id": {"evt_g19": _evt("evt_g19", "2026-08-19", "disaster_response")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-19", "refresh_batch_id": "dr_s",
         "expected_change_required": True, "expected_review": True},
        {"case_id": "snap_20_poll_review", "previous_state": base_state,
         "previous_supporting": [], "previous_snapshot_id": "tn_state_20260801_v1",
         "new_event_ids": ["evt_g20"], "events_by_id": {"evt_g20": _evt("evt_g20", "2026-08-20", "poll_release")},
         "coverage": {"coverage_version": "x", "built_from_formal_state_hash": "h"},
         "as_of": "2026-08-20", "refresh_batch_id": "dr_t",
         "expected_change_required": True, "expected_review": True},
    ]


def build_trigger_cases() -> list[dict]:
    return [
        {"case_id": "trg_01_day9", "run_date": "2026-08-09", "facts_cutoff": "2026-07-31",
         "expected_start": "2026-07-16", "expected_end": "2026-07-31",
         "expected_eligible": True, "expected_status": "eligible"},
        {"case_id": "trg_02_day22", "run_date": "2026-08-22", "facts_cutoff": "2026-08-15",
         "expected_start": "2026-08-01", "expected_end": "2026-08-15",
         "expected_eligible": True, "expected_status": "eligible"},
        {"case_id": "trg_03_day8_pending", "run_date": "2026-08-08", "facts_cutoff": "2026-07-31",
         "expected_start": "2026-08-01", "expected_end": "2026-08-15",
         "expected_eligible": False, "expected_status": "pending", "expected_reason": "not_reporting_day"},
        {"case_id": "trg_04_day10_pending", "run_date": "2026-08-10", "facts_cutoff": "2026-07-31",
         "expected_start": "2026-08-01", "expected_end": "2026-08-15",
         "expected_eligible": False, "expected_status": "pending", "expected_reason": "not_reporting_day"},
        {"case_id": "trg_05_day21_pending", "run_date": "2026-08-21", "facts_cutoff": "2026-08-15",
         "expected_start": "2026-08-16", "expected_end": "2026-08-31",
         "expected_eligible": False, "expected_status": "pending", "expected_reason": "not_reporting_day"},
        {"case_id": "trg_06_day23_pending", "run_date": "2026-08-23", "facts_cutoff": "2026-08-15",
         "expected_start": "2026-08-16", "expected_end": "2026-08-31",
         "expected_eligible": False, "expected_status": "pending", "expected_reason": "not_reporting_day"},
        {"case_id": "trg_07_month_end", "run_date": "2026-08-31", "facts_cutoff": "2026-08-31",
         "expected_start": "2026-08-16", "expected_end": "2026-08-31",
         "expected_eligible": False, "expected_status": "pending", "expected_reason": "not_reporting_day"},
        {"case_id": "trg_08_leap_feb_22", "run_date": "2028-02-22", "facts_cutoff": "2028-02-15",
         "expected_start": "2028-02-01", "expected_end": "2028-02-15",
         "expected_eligible": True, "expected_status": "eligible"},
        {"case_id": "trg_09_leap_feb_9", "run_date": "2028-02-09", "facts_cutoff": "2028-01-31",
         "expected_start": "2028-01-16", "expected_end": "2028-01-31",
         "expected_eligible": True, "expected_status": "eligible"},
        {"case_id": "trg_10_non_leap_feb_9", "run_date": "2027-02-09", "facts_cutoff": "2027-01-31",
         "expected_start": "2027-01-16", "expected_end": "2027-01-31",
         "expected_eligible": True, "expected_status": "eligible"},
        {"case_id": "trg_11_coverage_gap_report_day", "run_date": "2026-08-09", "facts_cutoff": "2026-07-30",
         "expected_start": "2026-07-16", "expected_end": "2026-07-31",
         "expected_eligible": False, "expected_status": "pending",
         "expected_reason": "report_day_coverage_insufficient_draft_allowed"},
        {"case_id": "trg_12_snapshot_pending_blocked", "run_date": "2026-08-09", "facts_cutoff": "2026-07-31",
         "snapshot_pending": True, "expected_eligible": False, "expected_status": "blocked"},
        {"case_id": "trg_13_duplicate_same_hash", "run_date": "2026-08-09", "facts_cutoff": "2026-07-31",
         "expected_start": "2026-07-16", "expected_end": "2026-07-31",
         "duplicate_same_hash": True, "expected_status": "eligible", "expected_eligible": True},
        {"case_id": "trg_14_new_hash_supersede", "run_date": "2026-08-08", "facts_cutoff": "2026-08-15",
         "expected_start": "2026-08-01", "expected_end": "2026-08-15",
         "supersede_old": True, "expected_status": "pending", "expected_eligible": False},
        {"case_id": "trg_15_manual", "run_date": "2026-08-08", "facts_cutoff": "2026-08-15",
         "manual": True, "expected_start": "2026-08-01", "expected_end": "2026-08-15",
         "expected_eligible": True, "expected_status": "eligible"},
    ]


def build_semantic_cases() -> list[dict]:
    """30 coverage semantic golden cases (20 calibration + 10 holdout)."""
    cal = [
        {"case_id": "sem_01_cutoff_equals_end", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e1", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-27"},
        {"case_id": "sem_02_cutoff_after_end", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e2", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-08-02", "expected_status": "full",
         "expected_facts_cutoff": "2026-08-02", "expected_latest_event_date": "2026-07-27"},
        {"case_id": "sem_03_cutoff_before_end", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e3", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-27", "expected_status": "partial",
         "expected_facts_cutoff": "2026-07-27", "expected_latest_event_date": "2026-07-27",
         "expected_uncovered_contains": "2026-07-28"},
        {"case_id": "sem_04_last_event_before_cutoff", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e4", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-27"},
        {"case_id": "sem_05_no_events_reviewed", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [], "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": None},
        {"case_id": "sem_06_second_half_unreviewed", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e6", "2026-07-20", "campaign_event")],
         "facts_cutoff": "2026-07-23", "expected_status": "partial",
         "expected_latest_event_date": "2026-07-20",
         "expected_uncovered_contains": "2026-07-24"},
        {"case_id": "sem_07_many_events_one_day", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e7a", "2026-07-27", "campaign_event"),
                    _evt("e7b", "2026-07-27", "poll_release")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_latest_event_date": "2026-07-27", "expected_event_count": 2},
        {"case_id": "sem_08_blocking_gap", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e8", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-31",
         "blocking_gaps": [{"kind": "missing_required_dimension", "reason": "x"}],
         "expected_status": "partial", "expected_blocking_count": 1},
        {"case_id": "sem_09_non_blocking_gap", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e9", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-31",
         "known_gaps": ["soft_limitation only"], "expected_status": "full"},
        {"case_id": "sem_10_no_event_day", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e10", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_uncovered_count": 0},
        {"case_id": "sem_11_no_poll_period", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e11", "2026-07-27", "campaign_event")], "polls": [],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_poll_cutoff": None},
        {"case_id": "sem_12_poll_cutoff_early", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e12", "2026-07-27", "campaign_event")],
         "polls": [_poll("p12", "2026-07-18")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_poll_cutoff": "2026-07-18"},
        {"case_id": "sem_13_latest_before_end", "subset": "calibration",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e13", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_latest_event_date": "2026-07-27"},
        {"case_id": "sem_14_cross_month", "subset": "calibration",
         "period_start": "2026-06-16", "period_end": "2026-07-15",
         "events": [_evt("e14", "2026-06-30", "campaign_event")],
         "facts_cutoff": "2026-07-15", "expected_status": "full",
         "expected_latest_event_date": "2026-06-30"},
        {"case_id": "sem_15_month_end", "subset": "calibration",
         "period_start": "2026-01-01", "period_end": "2026-01-31",
         "events": [_evt("e15", "2026-01-31", "campaign_event")],
         "facts_cutoff": "2026-01-31", "expected_status": "full",
         "expected_latest_event_date": "2026-01-31"},
        {"case_id": "sem_16_leap_feb", "subset": "calibration",
         "period_start": "2028-02-01", "period_end": "2028-02-29",
         "events": [_evt("e16", "2028-02-15", "campaign_event")],
         "facts_cutoff": "2028-02-29", "expected_status": "full",
         "expected_latest_event_date": "2028-02-15"},
        {"case_id": "sem_17_non_leap_feb", "subset": "calibration",
         "period_start": "2027-02-01", "period_end": "2027-02-28",
         "events": [_evt("e17", "2027-02-15", "campaign_event")],
         "facts_cutoff": "2027-02-28", "expected_status": "full",
         "expected_latest_event_date": "2027-02-15"},
        {"case_id": "sem_18_start_no_event", "subset": "calibration",
         "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("e18", "2026-07-10", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_latest_event_date": "2026-07-10"},
        {"case_id": "sem_19_end_no_event", "subset": "calibration",
         "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [_evt("e19", "2026-07-10", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_latest_event_date": "2026-07-10"},
        {"case_id": "sem_20_empty_events_reviewed", "subset": "calibration",
         "period_start": "2026-07-01", "period_end": "2026-07-31",
         "events": [], "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_latest_event_date": None},
        # ---- holdout 21-30 ----
        {"case_id": "sem_21_cutoff_after_end_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e21", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-08-05", "expected_status": "full",
         "expected_facts_cutoff": "2026-08-05", "expected_latest_event_date": "2026-07-27"},
        {"case_id": "sem_22_cutoff_missing_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e22", "2026-07-27", "campaign_event")],
         "facts_cutoff": None, "expected_status": "partial",
         "expected_facts_cutoff": None, "expected_latest_event_date": "2026-07-27",
         "expected_blocking_count": 1},
        {"case_id": "sem_23_unreviewed_blocking_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e23", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-27", "expected_status": "partial",
         "expected_blocking_count": 1},
        {"case_id": "sem_24_empty_reviewed_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [], "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_latest_event_date": None, "expected_uncovered_count": 0},
        {"case_id": "sem_25_no_poll_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e25", "2026-07-27", "campaign_event")], "polls": [],
         "facts_cutoff": "2026-07-31", "expected_status": "full"},
        {"case_id": "sem_26_latest_equals_cutoff_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e26", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-27", "expected_status": "partial",
         "expected_facts_cutoff": "2026-07-27", "expected_latest_event_date": "2026-07-27"},
        {"case_id": "sem_27_latest_before_cutoff_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e27", "2026-07-20", "campaign_event")],
         "facts_cutoff": "2026-07-31", "expected_status": "full",
         "expected_facts_cutoff": "2026-07-31", "expected_latest_event_date": "2026-07-20"},
        {"case_id": "sem_28_leap_feb_holdout", "subset": "holdout",
         "period_start": "2028-02-01", "period_end": "2028-02-29",
         "events": [], "facts_cutoff": "2028-02-29", "expected_status": "full",
         "expected_latest_event_date": None},
        {"case_id": "sem_29_non_leap_feb_holdout", "subset": "holdout",
         "period_start": "2027-02-01", "period_end": "2027-02-28",
         "events": [], "facts_cutoff": "2027-02-27", "expected_status": "partial",
         "expected_uncovered_contains": "2027-02-28"},
        {"case_id": "sem_30_multi_blocking_holdout", "subset": "holdout",
         "period_start": "2026-07-16", "period_end": "2026-07-31",
         "events": [_evt("e30", "2026-07-27", "campaign_event")],
         "facts_cutoff": "2026-07-27",
         "blocking_gaps": [{"kind": "unresolved_conflict", "reason": "c"}],
         "expected_status": "partial", "expected_blocking_count": 2},
    ]
    return cal


def build_case_catalog() -> dict:
    return {
        "pipeline": "post_publication_pipeline",
        "fixture_kind": "isolated_test_fixture",
        "cases": {
            "A": "new event -> coverage updated -> snapshot no change -> non-report day -> assessment pending",
            "B": "new event changes deterministic snapshot field -> candidate -> validator pass -> auto activate",
            "C": "new event touches analytical snapshot field -> review_required -> no auto activation -> assessment blocked",
            "D": "new event published but coverage rebuild fails -> facts stay -> old coverage stays -> refresh failed",
            "E": "coverage succeeds, snapshot staging fails -> coverage retained -> active snapshot unchanged",
            "F": "snapshot commit interrupted -> journal detected -> recovery -> exactly one active",
            "G": "snapshot succeeds, mock assessment fails -> no snapshot rollback -> trigger retry",
            "H": "report day + full coverage -> mock assessment final format generated",
            "I": "report day + incomplete coverage -> draft_with_data_gap -> no formal delivery",
            "J": "duplicate consumption of same refresh request -> no duplicate coverage/snapshot/trigger",
            "K": "new facts in same period -> old pending trigger superseded",
            "L": "refresh request after publication rollback -> consumption rejected",
        },
        "production_real_commit_performed": False,
        "production_real_snapshot_activation_performed": False,
        "production_real_coverage_commit_performed": False,
        "production_real_assessment_delivery_performed": False,
    }


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    SEMANTIC_OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "golden_coverage_cases.json").write_text(
        json.dumps(build_coverage_cases(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUT / "golden_snapshot_cases.json").write_text(
        json.dumps(build_snapshot_cases(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUT / "golden_trigger_cases.json").write_text(
        json.dumps(build_trigger_cases(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUT / "case_catalog.json").write_text(
        json.dumps(build_case_catalog(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (SEMANTIC_OUT / "coverage_semantic_golden_v1.json").write_text(
        json.dumps(build_semantic_cases(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUT / "README.md").write_text(
        "\n".join(
            [
                "# Phase 3/3.5 隔离测试 Fixture",
                "",
                "本目录仅用于隔离测试，不引用真实 `news.db`、真实 `election_context.db` 或真实候选库。",
                "- `golden_coverage_cases.json`：20 组 Coverage 黄金案例（Phase 3.5 权威语义）",
                "- `golden_snapshot_cases.json`：20 组 Snapshot 黄金案例",
                "- `golden_trigger_cases.json`：15 组 Assessment Trigger 黄金案例",
                "- `case_catalog.json`：端到端 Cases A–L 定义",
                "",
                "另见 `tests/fixtures/election_candidates/coverage_semantic_golden_v1.json`：",
                "30 组 Coverage 语义黄金案例（20 calibration + 10 holdout）。",
                "",
                "运行 `python scripts/build_phase3_fixtures.py` 可确定性重建。",
            ]
        ),
        encoding="utf-8",
    )
    print(f"wrote fixtures to {OUT} and {SEMANTIC_OUT}")


if __name__ == "__main__":
    main()
